In [2]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vinny\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [57]:
print("File to read:")
filename = input()
df = pd.read_csv(filename)
df

File to read:
scraped_videos.csv

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,9I9-uVUFLEw,"Trastornos oncológicos, neurológico y fase ter...",2020-10-24T18:18:12Z,UCXp1aqIieRQ7HnMdb1hh4WA,Clases de Apoyo - FM Enfermería,27,21.27.04,[none],94,3,0,0,https://i.ytimg.com/vi/9I9-uVUFLEw/default.jpg,False,False,"Clase dada por Emilio Gonzalez, estudiante de ..."
1,HDxXsS9QCiI,Riko Basic tani wózek dziecięcy 3w1 2w1,2019-01-29T12:23:12Z,UCZ3L1p0a7orG7lYvBVb1AvA,EURO-CART wózki dziecięce,22,21.27.04,tani wózek|riko basic|wózek basic|wózek basik|...,79867,111,9,32,https://i.ytimg.com/vi/HDxXsS9QCiI/default.jpg,False,False,"Szukasz taniego wózka dziecięcego 3w1 lub 2w1,..."
2,1ittmkW5u1I,48 Extreme Flight MXS-EXP “Beater”,2015-02-13T11:30:01Z,UCvrwZrKFfn3fxbkpiSIW4UQ,TripleThreatRC,28,21.27.04,Extreme Flight MXS EXP|TripleThreatRC|rgthd007...,8690,96,3,60,https://i.ytimg.com/vi/1ittmkW5u1I/default.jpg,False,False,This is forgotten footage from New Years Day a...
3,B0XAFo9dCsY,WC4: Top 10 Generals!,2018-07-28T18:18:44Z,UC9BAR73kn29UV4rrfrZGJ-A,juljas,20,21.27.04,juljas|wc4 generals|wc4 mod|world conqueror 4|...,16405,301,15,115,https://i.ytimg.com/vi/B0XAFo9dCsY/default.jpg,False,False,https://www.strawpoll.me/16166818 would you jo...
4,Vk-Y6LhK23o,#t9p,2019-01-03T12:07:38Z,UCr2xXMcS9cWwQPtkdYeXZig,Top10 Tik Tok LIKE Funny,22,21.27.04,[none],1,0,0,0,https://i.ytimg.com/vi/Vk-Y6LhK23o/default.jpg,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17742,AUZxd0Vipf4,2021 - KW2,2021-01-11T07:44:31Z,UClfn0cfOqCpnF0wXFg_KZxQ,Infokanal St. Michael i.O.,24,21.28.04,[none],32,0,0,0,https://i.ytimg.com/vi/AUZxd0Vipf4/default.jpg,False,False,NaN
17743,-Pbsg66-1RQ,De badkamer en het AREI,2021-03-09T23:00:16Z,UC3Nl4OEJI-vH0p5Ct4J_7ig,hans staessens,27,21.28.04,Badkamer|elektro|elektriciteit|lekstroom|verli...,215,7,0,0,https://i.ytimg.com/vi/-Pbsg66-1RQ/default.jpg,True,False,In deze video geeft Mr. Staessens uitleg over ...
17744,yCec7d_-E8o,This Bag Is Huge,2021-04-21T21:49:45Z,UCajF-Cvbwmy7a2e5R4YIHGA,Phil Gates,28,21.28.04,south africa|university student|student life|u...,45,11,0,0,https://i.ytimg.com/vi/yCec7d_-E8o/default.jpg,False,False,In this video I will just be talking about thi...
17745,ULif9pQ3g78,TÜRKİYE U16: 4 - PORTEKİZ U16: 3,2019-11-30T17:45:08Z,UCPBvVNQ6x_GC1elB-h8truw,Live Sport,17,21.28.04,[none],20967,186,7,16,https://i.ytimg.com/vi/ULif9pQ3g78/default.jpg,False,False,"U16 Milli Takımımız, Antalya'da düzenlenen Ulu..."
17746,gOGbhVvdypw,TYH TY-16 PHANTASM (TOY DJI CLONE) 720P HD WIF...,2018-04-23T11:16:57Z,UCu9W2fjJrH8E6aa1AQuSD4A,PERTH WEST OZ RC,24,21.28.04,dji mavic air|dji spark|mavic air|spark drone|...,11746,86,6,34,https://i.ytimg.com/vi/gOGbhVvdypw/default.jpg,False,False,Purchase link to thisTYH TY-T6 Phantasm Wifi F...

In [37]:
np.percentile(np.exp(df['log_norm_views']), 10)

307493.5000000001

In [58]:
def percent_capital(title):
    number_capitals = sum(1 for c in str(title) if c.isupper())
    number_overall = len(str(title))
    return number_capitals / number_overall

In [59]:
def title_length(title):
    return len(str(title))

In [60]:
def question_mark(title):
    if "?" in str(title): 
        return True
    else:
        return False

In [61]:
def exclamation_mark(title):
    if "!" in str(title): 
        return True
    else:
        return False

In [62]:
def fully_capital(title):
    tokens = str(title).split()
    for token in tokens:
        if(token.isupper()):
            return True
    return False

In [63]:
def isEnglish(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

In [64]:
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()
def get_sentiment(title):
    return sia.polarity_scores(str(title))["compound"]

In [65]:
def number_fully_capital(title):
    count = 0
    tokens = str(title).split()
    for token in tokens:
        if(token.isupper()):
            count+=1
    return count

# SCRUBBING

In [66]:
# for scraped data
df = df[df['video_id'] != 'video_id']

In [67]:
df = df.drop(columns=['video_id', 'trending_date', 'channelTitle', 'categoryId', 'publishedAt', 'tags', 'thumbnail_link', 'comments_disabled', 'ratings_disabled', 'description', 'channelId','comment_count','likes','dislikes'])
df

                                                   title view_count
0      Trastornos oncológicos, neurológico y fase ter...         94
1                Riko Basic tani wózek dziecięcy 3w1 2w1      79867
2                     48 Extreme Flight MXS-EXP “Beater”       8690
3                                  WC4: Top 10 Generals!      16405
4                                                   #t9p          1
...                                                  ...        ...
17742                                         2021 - KW2         32
17743                            De badkamer en het AREI        215
17744                                   This Bag Is Huge         45
17745                   TÜRKİYE U16: 4 - PORTEKİZ U16: 3      20967
17746  TYH TY-16 PHANTASM (TOY DJI CLONE) 720P HD WIF...      11746

[17400 rows x 2 columns]

# FEATURE CREATION

In [68]:
m = df['title'].apply(isEnglish)
df = df[m]
df

                                                   title view_count
3                                  WC4: Top 10 Generals!      16405
4                                                   #t9p          1
5                                           7TB.1 ON TOP          2
8      Freedom Planet Speedrun - Lilac - Pangu Lagoon...         11
9        Oh no oh no oh no no no song | TikTok Challenge    3994380
...                                                  ...        ...
17741  NDA MATHS 2021 - FULL ANSWER KEY & SOLUTION SE...      56906
17742                                         2021 - KW2         32
17743                            De badkamer en het AREI        215
17744                                   This Bag Is Huge         45
17746  TYH TY-16 PHANTASM (TOY DJI CLONE) 720P HD WIF...      11746

[11761 rows x 2 columns]

In [69]:
df['percent_capital'] = df['title'].apply(percent_capital)
df['title_length'] = df['title'].apply(title_length)
df['contains_question_mark'] = df['title'].apply(question_mark)
df['contains_exclamation_mark'] = df['title'].apply(exclamation_mark)
df['VADER'] = df['title'].apply(get_sentiment)
df['has_full_cap_word'] = df['title'].apply(fully_capital)
df['full_cap_count'] = df['title'].apply(number_fully_capital)

C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [70]:
def tanh_normalizer(value, column_name):
    return 0.5 * (np.tanh(0.01 * ( value - np.mean(df[column_name])) / np.std(df[column_name])) + 1)

# TANH NORMALIZATION

In [71]:
df['title_length'] = df['title_length'].apply(lambda value : tanh_normalizer(value, 'title_length'))
df['VADER'] = df['VADER'].apply(lambda value : tanh_normalizer(value, 'VADER'))
df['full_cap_count'] = df['full_cap_count'].apply(lambda value : tanh_normalizer(value, 'full_cap_count'))

C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\vinny\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [73]:
df

,title,view_count,percent_capital,title_length,contains_question_mark,contains_exclamation_mark,VADER,has_full_cap_word,full_cap_count
3,WC4: Top 10 Generals!,16405,0.190476,0.495391,False,True,0.505091,True,0.498229
4,#t9p,1,0.000000,0.491927,False,False,0.499362,False,0.496068
5,7TB.1 ON TOP,2,0.583333,0.493557,False,False,0.503632,True,0.502552
8,Freedom Planet Speedrun - Lilac - Pangu Lagoon...,11,0.109375,0.504155,False,False,0.512803,False,0.496068
9,Oh no oh no oh no no no song | TikTok Challenge,3994380,0.085106,0.500690,False,False,0.481913,False,0.496068
...,...,...,...,...,...,...,...,...,...
17741,NDA MATHS 2021 - FULL ANSWER KEY & SOLUTION SE...,56906,0.641975,0.507619,False,True,0.516324,True,0.517674
17742,2021 - KW2,32,0.200000,0.493150,False,False,0.499362,True,0.498229
17743,De badkamer en het AREI,215,0.217391,0.495799,False,False,0.499362,True,0.498229
17744,This Bag Is Huge,45,0.250000,0.494372,False,False,0.506078,False,0.496068
17746,TYH TY-16 PHANTASM (TOY DJI CLONE) 720P HD WIF...,11746,0.700000,0.503339,False,False,0.499362,True,0.519832

In [74]:
print("Save file as:")
filename = input()
df.to_csv(filename, index=False)

Save file as:
only_english_scraped_data.csv

# Merging trending and non-trending

In [75]:
trending_df = pd.read_csv('US_processed_trending_data.csv')
non_trending_df = pd.read_csv('only_english_scraped_data.csv')

In [76]:
non_trending_df = non_trending_df[non_trending_df['view_count'] < 307494]

In [77]:
non_trending_df.shape

(10482, 9)

In [79]:
#Don't need views anymore
non_trending_df = non_trending_df.drop(columns=['view_count'])
trending_df = trending_df.drop(columns=['log_norm_views'])

In [83]:
# Add column for whether vid was trending or not
non_trending_df['trending'] = False
trending_df['trending'] = True

In [84]:
non_trending_df.head()

,title,percent_capital,title_length,contains_question_mark,contains_exclamation_mark,VADER,has_full_cap_word,full_cap_count,trending
0,WC4: Top 10 Generals!,0.190476,0.495391,False,True,0.505091,True,0.498229,False
1,#t9p,0.000000,0.491927,False,False,0.499362,False,0.496068,False
2,7TB.1 ON TOP,0.583333,0.493557,False,False,0.503632,True,0.502552,False
3,Freedom Planet Speedrun - Lilac - Pangu Lagoon...,0.109375,0.504155,False,False,0.512803,False,0.496068,False
5,Logs Everything You Need to Know,0.156250,0.497633,False,False,0.499362,False,0.496068,False

In [85]:
trending_df.head()

,title,percent_capital,title_length,contains_question_mark,contains_exclamation_mark,VADER,has_full_cap_word,full_cap_count,trending
0,I ASKED HER TO BE MY GIRLFRIEND...,0.735294,0.495897,False,False,0.499711,True,0.514066,True
1,Apex Legends | Stories from the Outlands – “Th...,0.100000,0.502210,False,False,0.499711,False,0.496822,True
2,I left youtube for a month and THIS is what ha...,0.094340,0.500510,False,False,0.499711,True,0.501750,True
3,XXL 2020 Freshman Class Revealed - Official An...,0.142857,0.501239,False,False,0.499711,True,0.499286,True
4,Ultimate DIY Home Movie Theater for The LaBran...,0.200000,0.500996,False,True,0.499711,True,0.499286,True

In [87]:
## We want equal trending and non trending
sample = trending_df.sample(n = 10482)
sample.head()

,title,percent_capital,title_length,contains_question_mark,contains_exclamation_mark,VADER,has_full_cap_word,full_cap_count,trending
49948,"Catching up with Sis Mukbang, season 2 reality...",0.057692,0.500268,True,False,0.499711,False,0.496822,True
40013,There is a new kind of pack for The Sims 4...,0.066667,0.498568,False,False,0.499711,False,0.496822,True
44724,SO I MET TRICKY THE CLOWN & HE IS NO JOKE. | F...,0.507692,0.503424,False,False,0.491669,True,0.521448,True
6200,Texans vs. Chiefs Week 1 Highlights | NFL 2020,0.152174,0.498811,False,False,0.499711,True,0.499286,True
32332,How to Break the Ice - Submarine Edition #shorts,0.104167,0.499296,False,False,0.499711,False,0.496822,True

In [88]:
sample.shape

(10482, 9)

In [89]:
##combine
total_df = pd.concat([sample, non_trending_df], axis=0)

In [90]:
## shuffle
total_df = total_df.sample(frac=1)
total_df

,title,percent_capital,title_length,contains_question_mark,contains_exclamation_mark,VADER,has_full_cap_word,full_cap_count,trending
8051,"Dana White recaps Colby Covington’s win, Khamz...",0.208333,0.505124,False,False,0.508916,True,0.504214,True
39483,BANDA MS - LA CASITA (VIDEO OFICIAL),0.750000,0.496383,False,False,0.499711,True,0.511603,True
16906,Blac Youngsta - I Met Tay Keith First (Officia...,0.160920,0.508765,False,False,0.499711,True,0.499286,True
7151,Farol Ltd | New 2020 John Deere 8RX 410 Road T...,0.173913,0.505173,False,False,0.499362,True,0.498229,False
33985,WHAT HAPPENED at UFC 257?! Conor McGregor vs D...,0.269663,0.509251,True,True,0.492816,True,0.504214,True
...,...,...,...,...,...,...,...,...,...
27384,Playing Among Us In Real Life 2!,0.187500,0.495411,False,True,0.503975,False,0.496822,True
421,How Hard Fighting Game Combos used to be,0.125000,0.497354,False,False,0.492792,False,0.496822,True
6881,Pembelajaran kata tanya WH5 question.,0.078947,0.498856,False,False,0.499362,True,0.498229,False
4794,PS4 de FlavioRato-L43,0.238095,0.495391,False,False,0.499362,True,0.498229,False
8969,KALAKAR!! | CHEETAH| (Prod. Space on the beat...,0.206186,0.510878,False,True,0.499362,True,0.500391,False

In [91]:
total_df.shape

(20964, 9)

In [92]:
total_df.to_csv('final_video_data.csv', index=False)